
export const FETCH_ALL_FEATURE_VALUES = 'FETCH_ALL_FEATURE_VALUES';
export const ADD_FEATURE_VALUE = 'ADD_FEATURE_VALUE';
export const UPDATE_FEATURE_VALUE = 'UPDATE_FEATURE_VALUE';
export const DELETE_FEATURE_VALUE = 'DELETE_FEATURE_VALUE';

export const FETCH_ALL_FEATURES = 'FETCH_ALL_FEATURES';
export const ADD_FEATURE = 'ADD_FEATURE';
export const UPDATE_FEATURE = 'UPDATE_FEATURE';
export const DELETE_FEATURE = 'DELETE_FEATURE';

export const FETCH_ALL_BRANCHES = 'FETCH_ALL_BRANCHES';
export const ADD_BRANCH = 'ADD_BRANCH';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const DELETE_BRANCH = 'DELETE_BRANCH';

export const FETCH_ALL_BANNERS = 'FETCH_ALL_BANNERS';
export const ADD_BANNER = 'ADD_BANNER';
export const UPDATE_BANNER = 'UPDATE_BANNER';
export const DELETE_BANNER = 'DELETE_BANNER';

export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';


export const FETCH_ALL_ORDERS = 'FETCH_ALL_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const GET_ORDER_ITEMS = 'GET_ORDER_ITEMS';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const GET_CATEGORY_PRODUCTS = 'GET_CATEGORY_PRODUCTS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_ALL_Products = 'FETCH_ALL_Products';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const ADD_IMAGE_TO_PRODUCT = 'ADD_IMAGE_TO_PRODUCT';
export const DELETE_PRODUCT_IMAGE = 'DELETE_PRODUCT_IMAGE';

export const FETCH_ALL_MESURES = 'FETCH_ALL_MESURES';